### ISSUE TITLE
Session-data field contains weird data and doesn't work properly 

### ISSUE THREAD

**Issue by luqmanulkhair** [AndreasKl/reactive-spring-session-vertx#151]

**Comment by AndreasKl** [comment]
Hi @luqmanulkhair thanks for your report. Could you explain a bit more what you mean with "weird data" and doesn't work.

The session data is persisted as serialized bytes. As Spring Security puts arbitrary Java serializable classes into the session, this is one way to deal with this and the same solution Tomcat and Spring chooses.

**Comment by luqmanulkhair** [comment]
It is not clear which datatype should I use. I used blob but then spring says it is not string type. I also tried varchar and text with encoding but then it says session is missing. From my perspective something is wrong with the datatype of session-data.

**Comment by AndreasKl** [comment]
Which database are you using? 

There are setup scripts for postgres and mysql:
https://github.com/AndreasKl/reactive-spring-session-vertx/blob/master/reactive-spring-session-mysql/src/main/resources/schema.sql
https://github.com/AndreasKl/reactive-spring-session-vertx/blob/master/reactive-spring-session-postgres/src/main/resources/schema.sql

And you can use: 
https://github.com/AndreasKl/reactive-spring-session-vertx/blob/master/reactive-spring-session-core/src/main/java/net/andreaskluth/session/core/support/ReactiveSessionSchemaPopulator.java
to prepare a database.

**Comment by luqmanulkhair** [comment]
@AndreasKl thanks its works however I want to delete the session data, how can I achieve it?

**Comment by AndreasKl** [comment]
Hi, nice to hear. 

The https://github.com/AndreasKl/reactive-spring-session-vertx/blob/master/reactive-spring-session-postgres/src/main/java/net/andreaskluth/session/postgres/ReactivePostgresSessionConfiguration.java#L24 contains a preconfigured scheduler that takes care of cleaning outdated sessions.

You could also manually call https://github.com/AndreasKl/reactive-spring-session-vertx/blob/master/reactive-spring-session-core/src/main/java/net/andreaskluth/session/core/ReactiveVertxSessionRepository.java#L245 , but make sure that you subscribe/block on the returned `Mono`.

**Comment by luqmanulkhair** [comment]
@AndreasKl thanks for it, I was manually invalidating session, I think it is then not working if the scheduler is doing it automatically. I want to manually invalidate the session and then want to see that the corresponding data from the database is also deleted. Is it the same for MySQL aswell?

**Comment by AndreasKl** [comment]
@luqmanulkhair It's the same. The queries for MySQL are located here `ReactiveMySQLSessionRepositoryQueries` and the config is just prefixed with MySQL. The watchdog is monitoring the `expiry_time`, if you want to enforce session cleanup in tests you could call the `cleanupExpiredSessions` explicitly or reduce the `maxInactiveInterval` time to a low value.

**Comment by luqmanulkhair** [comment]
@AndreasKl if I delete the session from the database, will it automatically be deleted from memory?

**Comment by luqmanulkhair** [comment]
@AndreasKl Is there someway where zoombies(login-process borken in the middle) are removed from the database?

**Comment by AndreasKl** [comment]
They are removed eventually when `maxInactiveInterval` is reached. The tuples stored in the session are quite small (a few bytes) and will vanish after being inactive for 30 minutes or whatever you configure. 

If you are running the code on production for somthing with non trivial scale you should monitor the session database anyway.

**Comment by luqmanulkhair** [comment]
@AndreasKl Last question about the example, you have set maxsize and maxwait queue, how does these values effect the scheduler. What values should I consider, why is 5 and 10 chosen, or are these random?  
new PoolOptions()
      .setMaxSize(5)
      .setMaxWaitQueueSize(10);

**Comment by AndreasKl** [comment]
For load-testing I used a small postgres instance on gcp (https://cloud.google.com/sql/docs/quotas#cloud-sql-for-postgresql-connection-limits). The application, based on Spring cloud gateway, handles the whole load of a quite largish fulfillment backend. There were 6 instances of these service handling the traffic, and I did not want to exhaust the 50 connection limit, even when an rolling deployment was running.

5 is for the amount of connections that are taken at a maximum. 10 is more or less arbitrary, as I never want in production that someone has to wait for a connection, but if things go bad; then I should get exceptions quite fast as 10 is a quite low value.

For an explanation of these setting you could have a look at:
https://vertx.io/docs/apidocs/io/vertx/sqlclient/PoolOptions.html
https://www.enterprisedb.com/postgres-tutorials/why-you-should-use-connection-pooling-when-setting-maxconnections-postgres
